<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Solution</name>
   <tag></tag>
   <elementGuidId>9839248b-7aa2-4da5-85c1-4e406a85b7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[2]/div[2]/div/div/div[2]/div/nav/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.border-sky-500.text-sky-600.whitespace-nowrap.border-b-2.px-1.py-4.text-sm.font-medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c3ab66c-bde4-4bb2-a710-00d554e56769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>def6cccc-b32f-4fd4-8d14-178b96ea425a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-sky-500 text-sky-600 whitespace-nowrap border-b-2 px-1 py-4 text-sm font-medium</value>
      <webElementGuid>9e8402f3-65e7-43e3-9b00-0227929e79ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solution</value>
      <webElementGuid>d7f4b825-0e3d-45b6-bc27-ce34a3f4a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex flex-1 pt-16&quot;]/main[@class=&quot;h-full w-full flex-1&quot;]/div[@class=&quot;pt-2&quot;]/div[@class=&quot;relative mx-auto max-w-7xl&quot;]/div[@class=&quot;m-6 flex flex-col gap-6 sm:flex-row&quot;]/div[@class=&quot;flex-grow&quot;]/div[@class=&quot;container mx-auto&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;hidden sm:block&quot;]/div[@class=&quot;border-b border-gray-200&quot;]/nav[@class=&quot;flex space-x-8&quot;]/a[@class=&quot;border-sky-500 text-sky-600 whitespace-nowrap border-b-2 px-1 py-4 text-sm font-medium&quot;]</value>
      <webElementGuid>6ea4945c-15f1-4764-93b8-5fc8945d17d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div[2]/div/div/div[2]/div/nav/a</value>
      <webElementGuid>10760711-fedd-423d-bd54-858e8aaf0886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Solution')]</value>
      <webElementGuid>ff5bd81e-2c16-41df-9f44-5ccb40b5b823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a tab'])[1]/following::a[1]</value>
      <webElementGuid>901f4d05-8f4f-4616-8f94-2ffa612bce0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software Development (0)'])[1]/following::a[1]</value>
      <webElementGuid>12105d6a-6e22-4831-a37c-7d6d3f10e288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Provisioning'])[1]/preceding::a[2]</value>
      <webElementGuid>9170a8d1-8a3e-4fbc-ac96-ed24319d6ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevOps'])[1]/preceding::a[3]</value>
      <webElementGuid>cfdc1b80-8283-448b-8be4-e260fb5d18f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>438230f2-a185-40f7-bf5a-f679311d40b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>4af424fd-4f5e-4380-a2b6-c6b56c46f1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Solution' or . = 'Solution')]</value>
      <webElementGuid>36d61d7c-ab72-46eb-b769-7aee960386c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
