<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category_h-4 w-4 rounded border-gray-_cd3b7e</name>
   <tag></tag>
   <elementGuidId>2ceaf61b-b09e-42c2-8444-21c656d0349e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.h-4.w-4.rounded.border-gray-300.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b2c300c-655a-4311-a39a-aeefba25ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3a773d83-adce-4a4b-b7bf-17910370cb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-4 w-4 rounded border-gray-300 text-primary</value>
      <webElementGuid>1402186c-b085-4489-a168-0a814e45b1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>22194e21-e951-4cf9-84d7-06a3982e5a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex flex-1 pt-16&quot;]/main[@class=&quot;h-full w-full flex-1&quot;]/div[@class=&quot;pt-2&quot;]/div[@class=&quot;relative mx-auto max-w-7xl&quot;]/div[@class=&quot;m-6 flex flex-col gap-6 sm:flex-row&quot;]/div[@class=&quot;h-min overflow-hidden rounded-lg border border-gray-200 bg-white sm:w-1/4&quot;]/div[@class=&quot;border-b p-4&quot;]/ul[@class=&quot;space-y-3&quot;]/li[1]/label[@class=&quot;inline-flex items-center&quot;]/input[@class=&quot;h-4 w-4 rounded border-gray-300 text-primary&quot;]</value>
      <webElementGuid>8f74b1ee-7a98-49e5-b2b2-274f0486a496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='9']</value>
      <webElementGuid>ba7120e5-8dc1-40f0-b824-197c398c2df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div[2]/ul/li/label/input</value>
      <webElementGuid>76413e81-7fc1-4830-9899-6f27136563b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1db5985b-f0db-4887-87db-8dac0a3e5eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>f2143cec-e702-45ed-a54a-c9a63d42f3eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
