<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Hello Divers  How can we help_h-5 w-5 t_baddd5</name>
   <tag></tag>
   <elementGuidId>b21a83ec-580c-4aec-9625-53ff903cb70e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.h-5.w-5.text-gray-400</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello Divers! 👋 How can we help?'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>38bb4308-c64b-41e6-bd37-e0aab2c17704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>55bb42b2-3986-410e-b704-4b430d7e47a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>bfba7966-d3b3-4749-9552-01ae22379ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>e6107896-e990-42a0-a3e8-5f5e8be6022f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>5b7145fd-0282-4661-a248-e01c617f7844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>10d75d6b-3798-43a8-beec-c41dba2a38d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>056d3e42-5f9e-46ab-b87f-04c8d2f30d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>12969696-4481-49c1-9647-b8fb4fe8729e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-5 w-5 text-gray-400</value>
      <webElementGuid>570e7400-64d8-477a-b648-296c64828f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;mt-16 w-full bg-blue-700 bg-cover p-6 py-12&quot;]/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;flex w-1/2 items-center pt-6&quot;]/div[@class=&quot;relative w-1/2 flex-grow flex-col items-center focus-within:z-10&quot;]/div[@class=&quot;absolute inset-y-0 right-0 flex items-center pr-3&quot;]/button[@class=&quot;focus:outline-none&quot;]/svg[@class=&quot;h-5 w-5 text-gray-400&quot;]</value>
      <webElementGuid>ef10d3a4-b4ce-4aed-b4fd-b8376423b1e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello Divers! 👋 How can we help?'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>2365f270-9e67-4dae-8593-9c4326718a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open user menu'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>4145d21d-318e-4463-9873-02c4cd0d5709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searching Results'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>dd2f5cf7-d61d-44e1-9d15-e9c0db459782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>c78a08fb-ac3e-49bf-b04f-96a80ba5252a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
