<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Task</name>
   <tag></tag>
   <elementGuidId>152cbf32-6b35-4cf4-b199-2c11aef5bafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div[2]/div[2]/div/nav/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a3a5bab-8382-4efc-8237-fa7fb55aba49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/project/29/task</value>
      <webElementGuid>4ef3a6e4-62f6-4c1a-912a-d57543f15fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 whitespace-nowrap border-b-2 px-1 py-4 text-sm font-medium</value>
      <webElementGuid>7ce0b68a-f989-49b6-85b8-3132c05cbd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Task</value>
      <webElementGuid>487153f3-065e-46e9-926d-3d3c5e3137f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex flex-1 pt-16&quot;]/main[@class=&quot;h-full w-full flex-1 dark:bg-gray-800 lg:pl-56&quot;]/div[@class=&quot;pt-4&quot;]/div[@class=&quot;mx-auto max-w-7xl&quot;]/div[1]/div[2]/div[@class=&quot;hidden sm:block&quot;]/div[@class=&quot;border-b border-gray-200 px-6&quot;]/nav[@class=&quot;-mb-px flex space-x-8&quot;]/a[@class=&quot;border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 whitespace-nowrap border-b-2 px-1 py-4 text-sm font-medium&quot;]</value>
      <webElementGuid>7ff482b3-fc77-4b50-aa4c-53d566085d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div[2]/div/nav/a[2]</value>
      <webElementGuid>968b4714-2d6f-4af1-8fda-74188f3bdbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Task')]</value>
      <webElementGuid>f25064e9-c2c0-4f87-b183-10eed6ad1dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[2]/following::a[1]</value>
      <webElementGuid>44b68f6b-5c2b-4e46-a252-6d1a154fe2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a tab'])[1]/following::a[2]</value>
      <webElementGuid>66eddf27-3bdd-4914-9fdd-21f841fee43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timeline'])[2]/preceding::a[1]</value>
      <webElementGuid>14172d1a-a4bd-4655-828e-29de135b47b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[2]/preceding::a[2]</value>
      <webElementGuid>2cb91c92-411e-40ad-aa62-a0187c008bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/project/29/task')]</value>
      <webElementGuid>91cfd9b2-31cd-4a88-be3c-808118c47484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a[2]</value>
      <webElementGuid>b1fc5da6-3a8f-4319-975e-07b4ea1a9d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/project/29/task' and (text() = 'Task' or . = 'Task')]</value>
      <webElementGuid>5660b66d-f5de-4318-aa5e-8f2622f07c43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
