<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View all quotations</name>
   <tag></tag>
   <elementGuidId>fec986f1-8de8-4594-a753-05e61f2d8126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div[3]/div[2]/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4793e4db-4cfe-4bf4-95a2-faea96e883f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/organization/quotation</value>
      <webElementGuid>8d9099af-7ba4-4ca7-bc30-13b74b9d1fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-medium leading-5 text-primary underline</value>
      <webElementGuid>74ca9643-feec-486b-b9a9-b8eb8edcc462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View all quotations </value>
      <webElementGuid>32e1ab97-d14d-4590-a3df-09656ec15a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex flex-1 pt-16&quot;]/main[@class=&quot;h-full w-full flex-1 dark:bg-gray-800&quot;]/div[@class=&quot;pt-4&quot;]/div[@class=&quot;m-7 max-w-full&quot;]/div[1]/div[@class=&quot;mx-4 flex flex-col&quot;]/div[@class=&quot;mb-6 grid grid-cols-1 gap-4 md:grid-cols-2&quot;]/div[@class=&quot;rounded-xl border border-neutral/outline bg-white p-5 shadow&quot;]/div[@class=&quot;mb-4&quot;]/p[@class=&quot;text-sm font-normal leading-5 text-on-surface-variant&quot;]/a[@class=&quot;text-sm font-medium leading-5 text-primary underline&quot;]</value>
      <webElementGuid>71e9516c-a420-4424-94ef-705aadc3d383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div[3]/div[2]/div/p/a</value>
      <webElementGuid>edddd0f5-32c3-4cc1-91eb-2e1f5d01cf2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View all quotations')]</value>
      <webElementGuid>0a104a74-c0b8-45b1-ba13-1826aedbf066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Quotations'])[1]/following::a[1]</value>
      <webElementGuid>618d29a6-acb8-47d5-84cf-7b9e504dbb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[1]</value>
      <webElementGuid>8d4624b2-4591-4558-8ba2-b7647c8286b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SO/2025/02/00234'])[1]/preceding::a[1]</value>
      <webElementGuid>63ec92e3-ad35-4b48-a481-c217288474d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sent'])[1]/preceding::a[1]</value>
      <webElementGuid>aaecad0b-ae83-4500-80e9-d19d74f097ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View all quotations']/parent::*</value>
      <webElementGuid>d2538ae6-4751-41ce-8d6f-e0566af62910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/organization/quotation')]</value>
      <webElementGuid>bf7a7113-5502-4cbf-8ced-0af6dc4743d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p/a</value>
      <webElementGuid>dd7ba2a6-7809-4f67-affa-fa430ce42c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/organization/quotation' and (text() = ' View all quotations ' or . = ' View all quotations ')]</value>
      <webElementGuid>c1f54d20-a981-4616-985e-dcba296af8e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
