<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Full Name Email Address Phone Company A_8c8afe</name>
   <tag></tag>
   <elementGuidId>e0cb624f-71a0-4e0f-b18b-81c96ea29bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-dialog-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='New Appointment'])[2]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39663994-595c-4095-9c62-75c359afc12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dialog-content</value>
      <webElementGuid>6ae0be1e-0f4b-4bff-898c-3fb232c5875e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>6bbd7fb5-3caa-4fa0-a984-5c8ebeb8c99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full Name *Email Address *Phone *Company Appointment Type *POCSubject *Message *Date / Time *Appointment Location </value>
      <webElementGuid>18b9b2d8-e688-4f57-8cdd-adaee3fa7d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-full bg-gray-50&quot;]/body[@class=&quot;h-full p-overflow-hidden&quot;]/div[@class=&quot;p-dialog-mask p-overlay-mask p-overlay-mask-enter&quot;]/div[@class=&quot;p-dialog p-component max-w-[600px]&quot;]/div[@class=&quot;p-dialog-content&quot;]</value>
      <webElementGuid>083fbe53-8658-48ba-ac6b-22c86f852c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Appointment'])[2]/following::div[2]</value>
      <webElementGuid>29352ad4-79ed-49ee-bf27-91b9e91bd5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::div[8]</value>
      <webElementGuid>1ab3aa1a-42e9-4756-a143-81dd3824f4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>dda42547-b14c-4573-969c-bc74cb1022da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Full Name *Email Address *Phone *Company Appointment Type *POCSubject *Message *Date / Time *Appointment Location ' or . = 'Full Name *Email Address *Phone *Company Appointment Type *POCSubject *Message *Date / Time *Appointment Location ')]</value>
      <webElementGuid>a54005f9-0192-42b1-a467-657fa2f52141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
