<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DevOps</name>
   <tag></tag>
   <elementGuidId>a919ddc0-70ed-4817-b6c5-cd2978027bbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='undefined_steppanel_1']/div/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>577a47e6-29f3-4339-8eae-02ccfefed54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2</value>
      <webElementGuid>f2b76d28-e9db-43bb-92d1-ac7dc62a922c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevOps</value>
      <webElementGuid>3be478f9-ab55-4345-b2d1-0ed27d0fd60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined_steppanel_1&quot;)/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[@class=&quot;col-span-2 rounded-lg border bg-white p-4&quot;]/div[@class=&quot;my-4 grid grid-cols-3 gap-2&quot;]/div[@class=&quot;cursor-pointer rounded-md border p-2 hover:bg-slate-100&quot;]/div[@class=&quot;mt-2&quot;]</value>
      <webElementGuid>74c3048e-9aac-4e24-b2b4-97a03cfd1a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='undefined_steppanel_1']/div/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>d6460756-1b6e-468c-af68-3f3323e5b702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solution / Cloud &amp; Hybrid Infrastructure'])[1]/following::div[3]</value>
      <webElementGuid>e0e1f3f7-479d-4e17-a7b5-5b5821a1c5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Provisioning'])[1]/following::div[4]</value>
      <webElementGuid>3667bc9c-c589-4d0c-8214-f3bec0ed79b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solution / Agile Secure Delivery'])[1]/preceding::div[1]</value>
      <webElementGuid>90eb1961-340b-448d-baf7-d7630ad026d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevSecOps'])[1]/preceding::div[3]</value>
      <webElementGuid>43290d7c-358b-47f3-a80c-7c7c210a5f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DevOps']/parent::*</value>
      <webElementGuid>e47aa62d-0a5a-40c7-94d4-0340fbc91a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>d89aaf24-bc38-4449-bee1-946bf7e89a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DevOps' or . = 'DevOps')]</value>
      <webElementGuid>4f5e27cb-7709-46f3-be50-6a1b63c796e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
