<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mean Time to Recover_meantimeToRecover</name>
   <tag></tag>
   <elementGuidId>0b1acc80-c988-4539-98f5-e28cfdcfa332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meantimeToRecover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='meantimeToRecover']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>015e7f04-c69f-41e1-a867-0579779e4763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meantimeToRecover</value>
      <webElementGuid>44dd2353-9b76-4202-b7b3-748131a24383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8951f59c-5118-4fae-9860-bb5aea18cf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8535baeb-c0c3-40ae-8788-62657cc7b3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>meantimeToRecover</value>
      <webElementGuid>509ccce4-23ae-47ef-aa40-95f6a8d6dcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>meantimeToRecover</value>
      <webElementGuid>b01c4966-b3ac-43a9-b95b-3b895b3c53e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g, 6</value>
      <webElementGuid>ab826724-8171-46dc-9722-bc4098316ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 py-1.5 pr-16 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 after:ml-0.5 after:text-red-500 after:content-['*'] focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>11a983fc-122e-4e50-b485-47d3912e354d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id8</value>
      <webElementGuid>d5c10f34-c5c9-4576-bb1c-2106aa434e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meantimeToRecover&quot;)</value>
      <webElementGuid>6706d1c7-1e68-408a-9e58-ab59e5abd065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='meantimeToRecover']</value>
      <webElementGuid>24e5479c-f55b-47e4-b564-a8946d3c948c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/form/div/div/div/div[4]/div[2]/input</value>
      <webElementGuid>a4cf2153-f19b-48c3-badb-7297ab4e533e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>7554b272-8205-4732-be95-d74c247854a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'meantimeToRecover' and @type = 'number' and @name = 'meantimeToRecover' and @placeholder = 'e.g, 6']</value>
      <webElementGuid>29d9a799-6130-439f-ba7f-5ad530926876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
