<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Change Failure Rate_changeFailureRate</name>
   <tag></tag>
   <elementGuidId>ab645a46-835a-4799-be9c-7929da7e0fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#changeFailureRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='changeFailureRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7c1fe45-1c46-4e31-9614-a276047e7d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changeFailureRate</value>
      <webElementGuid>2f0b3fa9-c546-4b44-995a-592505af41f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0bb90b93-e06b-4b6c-8ba5-7675ddc42b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e94d6601-d859-4bce-9445-304436a8b7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>changeFailureRate</value>
      <webElementGuid>ae10ba0d-004a-4cb6-8091-4e1f5b0e8b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>changeFailureRate</value>
      <webElementGuid>8cfb4d44-7541-45b0-8d76-ff26d70e9c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g, 15</value>
      <webElementGuid>8f8d9779-ddfa-4045-8c25-6a1c4b142055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 py-1.5 pr-8 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 after:ml-0.5 after:text-red-500 after:content-['*'] focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>2b4996b4-f692-44de-a8f5-621e29150d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id7</value>
      <webElementGuid>86e91ee3-8b78-4963-acae-7890e3e6cfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changeFailureRate&quot;)</value>
      <webElementGuid>f54c3d61-8e76-4671-9bf5-b800cd076801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='changeFailureRate']</value>
      <webElementGuid>75e8e672-bdb2-454c-888c-2d6654f73bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/form/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>3b0e019f-14c0-4ffb-87b4-7adb5375d7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>f39cc7d1-e798-4107-9009-8009385cbce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'changeFailureRate' and @type = 'number' and @name = 'changeFailureRate' and @placeholder = 'e.g, 15']</value>
      <webElementGuid>d39cdfad-294b-4aae-bc9a-cadf9dfe23be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
