<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deployment Frequency_deploymentFrequency</name>
   <tag></tag>
   <elementGuidId>52795219-7b8a-4710-a38f-000ff0168aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deploymentFrequency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='deploymentFrequency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b823419-07f0-4e49-8fa2-b5e87e77f773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deploymentFrequency</value>
      <webElementGuid>ad797d53-4ada-4bb7-a287-cdd11adb8b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b187d790-88c5-456c-98e4-804c982118c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d78413f6-4840-4c46-82a6-58c5a6cbcc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deploymentFrequency</value>
      <webElementGuid>99b5e687-3399-4f75-b88c-8474333e55bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>deploymentFrequency</value>
      <webElementGuid>cde208e0-2a0b-489c-ba4b-c7fbf934311c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g, 4</value>
      <webElementGuid>6f79a66b-c33a-4ef5-8492-ff1026332c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 py-1.5 pr-16 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>2dc97c34-7017-40d6-bff3-eb0385e6c816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id5</value>
      <webElementGuid>fffac100-b7ad-4135-ac8d-83af80bccecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deploymentFrequency&quot;)</value>
      <webElementGuid>e4d9aadb-9e37-4e31-bf9c-bfb0fe72f75b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='deploymentFrequency']</value>
      <webElementGuid>b7843e10-5610-40b1-9054-ae611d17e847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/form/div/div/div/div/div[2]/input</value>
      <webElementGuid>16e41e0f-a977-4327-a25a-2db1cc7ba487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>30d3a803-10f4-4c9e-a089-6e7ef3fece36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'deploymentFrequency' and @type = 'number' and @name = 'deploymentFrequency' and @placeholder = 'e.g, 4']</value>
      <webElementGuid>333743b6-539d-410b-9034-c5acde0acab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
