<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_infrastructureCost</name>
   <tag></tag>
   <elementGuidId>a4265010-f3e0-453f-8119-f8ea43187d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#infrastructureCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='infrastructureCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44e31e10-edad-4a87-85a0-e7af21dd9bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>infrastructureCost</value>
      <webElementGuid>b7db88ca-71ed-45eb-81cd-3b57bfb6f2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11abf5ed-c6cf-4f43-8217-08acd08c6ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>infrastructureCost</value>
      <webElementGuid>30666a11-76a9-450f-8649-b014b1e94c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>infrastructureCost</value>
      <webElementGuid>d831b60e-eada-4aae-8a00-f0061320f3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g, Rp 500.000.000</value>
      <webElementGuid>97d643ff-3e1b-4f00-800a-3b997c25121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 py-1.5 pl-8 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 after:ml-0.5 after:text-red-500 after:content-['*'] focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>e8da88ee-c4a3-4e5c-a654-f81d19ca4ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id11</value>
      <webElementGuid>c6999ca1-4dd3-4611-9985-ae9eb6b8b22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infrastructureCost&quot;)</value>
      <webElementGuid>45fa7d71-c74d-47a1-9034-a5310418ed72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='infrastructureCost']</value>
      <webElementGuid>be0cb856-8073-474c-ac8d-2cb8318cd0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/form/div/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>610f5f5a-d21d-46f0-8c11-73846c5b4dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>2f8573f4-80e6-4eac-a3b0-3c7a8a60c37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'infrastructureCost' and @type = 'text' and @name = 'infrastructureCost' and @placeholder = 'e.g, Rp 500.000.000']</value>
      <webElementGuid>7fb7a5fd-741a-4034-bd2c-3d5a3f777634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
