<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manage Service_Onsite</name>
   <tag></tag>
   <elementGuidId>3b5dc889-dcfb-4c4d-b87a-28a9a3752b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Onsite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Onsite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f6d874d-7446-4e55-b5f5-9879265b8089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Onsite</value>
      <webElementGuid>c32533f5-b875-436b-be4b-7a6959d376a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>90722190-8ef8-4b45-b25e-c5d96f782354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-input</value>
      <webElementGuid>385b197a-6431-4b6e-be3d-a4dd7e89f87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Onsite</value>
      <webElementGuid>a89f156a-e441-4144-960d-ed0403a5f9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2476795-a9f7-4c18-9253-0b8a9e5eb2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24,Onsite</value>
      <webElementGuid>b801f67c-951d-4dd8-a74c-164305ce4dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id14</value>
      <webElementGuid>20772216-b5b5-4e86-b480-7dd7d0578940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Onsite&quot;)</value>
      <webElementGuid>93affe45-680b-4c2b-ba36-017a811ecb9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Onsite']</value>
      <webElementGuid>d21d666c-4ae1-44ec-989a-851e54201eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-form']/div[2]/div/div/div/input</value>
      <webElementGuid>4b23f7c7-97f3-4d0d-baf2-39fd45b1dfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>bb689933-2863-4d37-92b8-7f313a9c6f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Onsite' and @type = 'radio' and @name = 'Onsite']</value>
      <webElementGuid>c37e5cab-34fb-4b18-a2c9-5d547c8d1b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
