<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_averageSalary</name>
   <tag></tag>
   <elementGuidId>72f93d99-6128-4ba6-a9ae-9ecafb7e2af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#averageSalary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='averageSalary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56aa2cc0-8944-49bd-9740-a58c891aa1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>averageSalary</value>
      <webElementGuid>1017e5f5-5148-4a90-8370-c41795f749d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53861593-556f-4a21-940a-04b5bf4766f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>averageSalary</value>
      <webElementGuid>5157fb0f-fec3-4bad-8e51-0b22a52ca126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>averageSalary</value>
      <webElementGuid>5943f40d-993d-491e-873b-99338c1509cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g, Rp 120.000.000</value>
      <webElementGuid>8187d50c-52f3-44a7-9f98-e802eb6bb5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 py-1.5 pl-8 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>55bd8571-abd3-439c-9455-7829def3dd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id9</value>
      <webElementGuid>298416aa-7522-4e26-be9c-a4f94591cac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;averageSalary&quot;)</value>
      <webElementGuid>9ddb683e-b2eb-486c-82d8-88a304ac25bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='averageSalary']</value>
      <webElementGuid>4c668fbc-99aa-42d7-920f-70030edd0249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/form/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>8214ccda-e481-44e4-9bff-331b3b22ffb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>78e3f080-850a-429a-bd4b-2c52a2324ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'averageSalary' and @type = 'text' and @name = 'averageSalary' and @placeholder = 'e.g, Rp 120.000.000']</value>
      <webElementGuid>f6914a49-13d4-4844-98fe-aa94c7b1e03a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
