<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manage Service_Docker</name>
   <tag></tag>
   <elementGuidId>34c75dbb-75d5-48b1-92ae-61d49516c5de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Docker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Docker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b5b0c11-0c77-4a2b-b149-7a22c9924c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Docker</value>
      <webElementGuid>225469ef-6b55-4a49-9123-2b0f3d71b16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3a333bc9-9da7-4815-b648-d5ddb7a58023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-input</value>
      <webElementGuid>345f852d-52f4-47f7-a8c7-e2311d155361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Docker</value>
      <webElementGuid>f2da4f0d-1529-4f3c-9ef1-5c2892d408cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7cf9207-01aa-49ea-a855-ee623ca9962c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>34,Docker</value>
      <webElementGuid>cab10384-2591-418b-9923-e1f62e2b30cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Docker&quot;)</value>
      <webElementGuid>f36b7199-8aaa-4619-a3fd-8ddb36579da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Docker']</value>
      <webElementGuid>1823ee76-c261-47a6-aec5-fbe1bc1846f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-form']/div[2]/div/div/input</value>
      <webElementGuid>c6a97963-eaeb-4f48-99a9-52deb3394e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a0a8af1a-7b32-4b0a-8c19-37300ebabfc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Docker' and @type = 'checkbox' and @name = 'Docker']</value>
      <webElementGuid>d33a1468-177c-4822-92fc-9754ef676609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
