<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_51-100</name>
   <tag></tag>
   <elementGuidId>6052e17e-9ce4-499f-842b-1755cc3c3968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pv_id_1_52_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_1_52_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fd101675-0519-4ba6-a0d4-00a06fd18439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_1_52_2</value>
      <webElementGuid>84bc0e0d-5fdc-4e69-abeb-1e7477e02e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-option</value>
      <webElementGuid>cec048bd-e564-4a72-aa6e-64ad63a96b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c8ff04e9-232a-4d0a-b149-663f6f443a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>51-100</value>
      <webElementGuid>9a2a570b-1195-481d-8c26-3b7c1e093c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7db42ada-026a-449f-ab0a-c442431e3458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b29c4d0a-39e3-4415-bafa-6f5cbef1a740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d69fae5a-29a8-433e-b78b-15195d21651a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a75886ee-b4cf-4d99-bd8a-3d230b6ff21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b6ea5b2-5c8f-438a-837e-02a59c8a96ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>49a628e6-e371-4118-a4b9-7e8478718317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ded374a5-b1f5-4ecf-8d27-094586dd7170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5126b072-edf5-45dd-83ee-954a4a476f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>51-100</value>
      <webElementGuid>cbc4ff41-18fc-4e81-bd1a-722f9bd9d985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_1_52_2&quot;)</value>
      <webElementGuid>c443cb51-a7a0-4e39-bf71-45484368bd52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pv_id_1_52_2']</value>
      <webElementGuid>3bb18a32-26f7-4458-a57c-eda23dc207fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_1_52_list']/li[3]</value>
      <webElementGuid>12165b19-6a32-499c-8d19-937f5c1e40a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::li[3]</value>
      <webElementGuid>7bb92411-a840-4aea-8b88-0726550b1b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::li[3]</value>
      <webElementGuid>9f1f2c4f-45df-451c-a3be-29f829cfc02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No selected item'])[1]/preceding::li[2]</value>
      <webElementGuid>e66efb03-7af9-44a6-92f3-d951b5f2c0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>1ce7d0f5-b9b6-435e-9e09-cf0a576631de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pv_id_1_52_2' and (text() = '51-100' or . = '51-100')]</value>
      <webElementGuid>28e2d545-4c58-449b-acf9-d245c30c7fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
