<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10-50</name>
   <tag></tag>
   <elementGuidId>dcd784bb-dc54-4eca-b46d-fd9558d87abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pv_id_1_50_1 > span.p-select-option-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_1_50_1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb1c82df-d3f7-4f63-abec-fdcfb39a6e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-option-label</value>
      <webElementGuid>665231ff-88b5-4be7-9a80-a709e992403d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>optionlabel</value>
      <webElementGuid>13605a2d-1337-44ee-8a3e-c82072ca2ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10-50</value>
      <webElementGuid>8c6870bb-31f1-4070-9c96-a30c47fd2c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_1_50_1&quot;)/span[@class=&quot;p-select-option-label&quot;]</value>
      <webElementGuid>11c9738b-fa3f-474a-a10e-9e2e94ea3e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pv_id_1_50_1']/span</value>
      <webElementGuid>a329ca4f-97cd-461d-ac2c-a143f0fc642d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::span[4]</value>
      <webElementGuid>d0e6d1be-1a9e-468f-8f79-4c1e07d6f0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::span[5]</value>
      <webElementGuid>febf9de0-70b1-42e8-a492-507d010bf34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No selected item'])[1]/preceding::span[3]</value>
      <webElementGuid>a8c9797b-8741-465c-a529-65fb14e5dab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10-50']/parent::*</value>
      <webElementGuid>63ae856a-f08f-420d-b00f-3d6d04440b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>2e2e803c-e3f3-4bfe-8026-4fe4ae9218b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '10-50' or . = '10-50')]</value>
      <webElementGuid>8406a6e5-2d34-444c-9a5d-d0907808a6ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
