<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Knowledge Center</name>
   <tag></tag>
   <elementGuidId>3638da3f-5cf5-4bc3-83f6-c8219bc01127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-v-0-9 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='headlessui-menu-item-v-0-9']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3386690-f889-48bc-a836-d0cfb4cc93ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Knowledge Center</value>
      <webElementGuid>3fc52c24-2e38-487a-83be-f816f36030c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-v-0-9&quot;)/span[1]</value>
      <webElementGuid>eef7c1e7-fd51-43ef-987c-b7f6ca92b287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='headlessui-menu-item-v-0-9']/span</value>
      <webElementGuid>cef2db40-7286-4bf5-bff1-de153b4e8f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/following::span[1]</value>
      <webElementGuid>7ea7883e-d6cc-4988-aade-8c3869058407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open user menu'])[1]/preceding::span[2]</value>
      <webElementGuid>0a056272-a188-488e-a55b-38441d3165c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good Afternoon Michael Oliver!'])[1]/preceding::span[3]</value>
      <webElementGuid>10a0df39-d729-4580-9162-93e1437381fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Knowledge Center']/parent::*</value>
      <webElementGuid>67916682-15b0-4457-a04e-246e0fa2f8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>21bb80ba-6069-4604-94ef-102927dbac62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Knowledge Center' or . = 'Knowledge Center')]</value>
      <webElementGuid>fac894fe-ebaf-4624-a7d9-e75df9975dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='headlessui-menu-item-v-1-9']/span</value>
      <webElementGuid>82fde443-e5a1-42eb-bace-5a35b30f1ebd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
