<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_License</name>
   <tag></tag>
   <elementGuidId>a1caa7df-49d5-4834-9dae-827e25e38470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pv_id_1_16_2 > span.p-select-option-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_1_16_2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0952bee5-5835-4715-9dec-8cf0bd0993c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-option-label</value>
      <webElementGuid>9dbff1e1-44d6-4fb7-a6a1-b74330f65d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>optionlabel</value>
      <webElementGuid>a3bb5cee-aafa-4c95-800e-7f171e0cfb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>License</value>
      <webElementGuid>ec812fe5-ccd9-4a15-98f9-20dd2af6452f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_1_16_2&quot;)/span[@class=&quot;p-select-option-label&quot;]</value>
      <webElementGuid>2b3f9d77-90b8-4ba6-9735-552ba9235d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pv_id_1_16_2']/span</value>
      <webElementGuid>fefde1c2-a9c8-4731-9f1d-8ba7efaab0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solution'])[1]/following::span[1]</value>
      <webElementGuid>f8a7de47-0fb5-44d8-bfdc-a6e3fe73574c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Filter'])[1]/following::span[2]</value>
      <webElementGuid>e4412b74-e42a-463d-a433-a43bd76cb27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>e3865fb2-1694-4612-a475-54a16729bd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'License' or . = 'License')]</value>
      <webElementGuid>6e58b078-38d6-4383-bfe9-b57dfa659493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
