<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Calculate</name>
   <tag></tag>
   <elementGuidId>9d8ab283-ef4c-4e37-8d57-15eca57c68fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e4a8024c-e1ff-42f0-936b-239f373b0671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label</value>
      <webElementGuid>296d3e89-fd64-4f35-a84b-6b973443ac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>15bddecf-a651-45eb-9eb8-488ba4c49233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>0e0139f5-3f97-46e2-8d4a-75e28eb0bc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex flex-1 pt-16&quot;]/main[@class=&quot;h-full w-full flex-1 dark:bg-gray-800 lg:pl-56&quot;]/div[@class=&quot;pt-4&quot;]/div[@class=&quot;h-full&quot;]/div[1]/div[@class=&quot;flex border-b p-4&quot;]/button[@class=&quot;p-button p-component p-button-sm&quot;]/span[@class=&quot;p-button-label&quot;]</value>
      <webElementGuid>218ee497-b907-4008-88d7-425261ea5dc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/button/span[2]</value>
      <webElementGuid>807473a5-29b0-4367-bacf-9353bd81e887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROI Calculator'])[3]/following::span[2]</value>
      <webElementGuid>72261438-f45e-49bc-8fea-912f893b5a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROI Calculator'])[2]/following::span[2]</value>
      <webElementGuid>8d93cb70-2e4a-423d-b3a5-384a223daa3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export to CSV'])[1]/preceding::span[2]</value>
      <webElementGuid>f2511100-a34a-45df-8465-c3f18bf23afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data Record'])[1]/preceding::span[3]</value>
      <webElementGuid>7a75eab9-f24c-4de8-97ff-e2565afb002a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calculate']/parent::*</value>
      <webElementGuid>081802fd-bbb1-4574-a0fc-cd01743cc686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/button/span[2]</value>
      <webElementGuid>db6bd720-f98b-4654-a63a-e0fcf6fba768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Calculate' or . = 'Calculate')]</value>
      <webElementGuid>76367025-5a3a-4950-bc69-b54f59dd0735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
