<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_11</name>
   <tag></tag>
   <elementGuidId>1a67f850-4c07-4ff0-acca-399998c7a2cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-datepicker-minute-picker > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datetime_panel']/div[2]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7b668f1-de40-4515-a3d8-0eb0cbfa30d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>minute</value>
      <webElementGuid>0dc50a19-841b-42a3-9584-8dff6b495da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-group-section</name>
      <type>Main</type>
      <value>timepickerlabel</value>
      <webElementGuid>959c352e-f391-4ecf-aea3-5dc9e6b19d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>d4b71673-faf6-4996-af32-58a2b1c9518f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datetime_panel&quot;)/div[@class=&quot;p-datepicker-time-picker&quot;]/div[@class=&quot;p-datepicker-minute-picker&quot;]/span[1]</value>
      <webElementGuid>631068bc-ecf9-4499-be6a-cd2cd2df8e27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datetime_panel']/div[2]/div[3]/span</value>
      <webElementGuid>6c4f36c1-510e-45d0-b4be-53ae7d355304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::span[1]</value>
      <webElementGuid>37cb22c4-8185-4e42-a120-50a0479832a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[45]</value>
      <webElementGuid>61b8a82b-49c0-4c4d-a52c-a29fca60291a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[1]</value>
      <webElementGuid>9c621530-7c43-4338-8a99-f5667fb6c8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[2]</value>
      <webElementGuid>f7b1935d-1c7d-4d05-9851-4ae5a83d88b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/span</value>
      <webElementGuid>b4feac68-e8ec-45fa-9f54-33bd1bd209db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '11' or . = '11')]</value>
      <webElementGuid>77f27c43-c83b-4fa9-ab15-387425967f27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
