<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__p-textarea p-component p-filled</name>
   <tag></tag>
   <elementGuidId>dce95332-b377-487b-840c-5b69d76990c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.p-textarea.p-component.p-filled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@value='T']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fddc706f-51f8-494c-9425-89a6c5b823af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-textarea p-component p-filled</value>
      <webElementGuid>4aa590b0-ef79-4688-9b70-534808cbfb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>54c681db-5e6f-4ca3-9e9c-f3856777140c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please discuss the details of the meeting.</value>
      <webElementGuid>12ece160-f511-4752-a78e-320d3b6a4420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c37ff617-01b0-4840-b7b9-1348b3ce6106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>ef2aa156-61e5-455c-8802-4f140e2cf88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>197b7b31-12e0-43ba-ae05-e38bce50a605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-full bg-gray-50&quot;]/body[@class=&quot;h-full p-overflow-hidden&quot;]/div[@class=&quot;p-dialog-mask p-overlay-mask p-overlay-mask-enter&quot;]/div[@class=&quot;p-dialog p-component max-w-[600px]&quot;]/div[@class=&quot;p-dialog-content&quot;]/div[@class=&quot;grid grid-cols-2 gap-2&quot;]/div[@class=&quot;col-span-2&quot;]/label[@class=&quot;flex flex-col gap-2&quot;]/textarea[@class=&quot;p-textarea p-component p-filled&quot;]</value>
      <webElementGuid>8dd9f2f1-f5ef-4f5f-b04e-19e847b0f20b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@value='T']</value>
      <webElementGuid>f7135164-af84-4372-ae63-355a79a72948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4ab301d5-0a00-4e4f-8f6d-e68e4b3bdadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Please discuss the details of the meeting.']</value>
      <webElementGuid>c98692c9-488c-41e8-a4b7-7233bd995401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
