<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_General Note_note</name>
   <tag></tag>
   <elementGuidId>8ed15937-d680-4275-9542-f0764ab4c8a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5ed40564-8db0-4298-b576-2849e500cff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-textarea p-component p-filled</value>
      <webElementGuid>4b0d0dfd-2b4e-4f2e-b547-f061d1843467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>99a510f7-09ae-4d62-a15a-5bef5b40d09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write a note</value>
      <webElementGuid>ccf8a17e-ae41-4611-b52a-85da1919f424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d07a6f06-eabf-45c3-9b3a-d4ac5de4cb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>c4d360e6-f2d1-4ea1-9153-5140f36115f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>b2347bb8-2bbc-4754-a70d-163a7bdd9060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note&quot;)</value>
      <webElementGuid>660f4ca0-d620-4daa-92a6-83a0a02a9ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='note']</value>
      <webElementGuid>25020523-bec9-491f-9d6f-7b88978c0351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='undefined_steppanel_2']/div/div[2]/div[2]/div[2]/textarea</value>
      <webElementGuid>dd84c74a-eccd-48a2-b6ef-ad17be39edc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>51ab3fb2-4747-409e-9fca-e4b8002974d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'note' and @placeholder = 'Write a note']</value>
      <webElementGuid>fb94d9c3-dbd2-48ba-b9d3-5391cd5c4ab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
