<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop</name>
   <tag></tag>
   <elementGuidId>0557789e-99e7-4c6b-b36e-2485e128920c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav/div/div[2]/div/div[2]/div[3]/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e011d35a-859f-44d3-a444-7b5f432468ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shop</value>
      <webElementGuid>c81429be-d489-4c6b-bba0-e4da88bf1d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex flex-nowrap items-center gap-x-2 px-2 pt-1 text-sm font-semibold border-b-2 border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700</value>
      <webElementGuid>0cf051f8-2adc-4ff3-ac52-774aa18c9c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Shop</value>
      <webElementGuid>0a5ca1e9-5e4b-4643-bc14-7013beef220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[@class=&quot;fixed top-0 z-50 w-full bg-white shadow&quot;]/div[1]/div[@class=&quot;mx-auto px-3 sm:pr-6 lg:pr-8&quot;]/div[@class=&quot;relative flex h-16 justify-between&quot;]/div[@class=&quot;flex flex-1 sm:items-stretch sm:justify-start&quot;]/div[@class=&quot;hidden sm:ml-6 sm:flex sm:gap-x-5&quot;]/a[@class=&quot;inline-flex flex-nowrap items-center gap-x-2 px-2 pt-1 text-sm font-semibold border-b-2 border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700&quot;]</value>
      <webElementGuid>e57fb5ce-569f-456f-900b-134ee1971827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav/div/div[2]/div/div[2]/div[3]/a[5]</value>
      <webElementGuid>5e65bf57-4601-48a2-a451-797be3924c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open user menu'])[1]/preceding::a[2]</value>
      <webElementGuid>9e212e07-c63f-45ab-b02a-7eb68f3999fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good Afternoon Michael Oliver!'])[1]/preceding::a[2]</value>
      <webElementGuid>1ee1576e-8316-4f46-aa21-94c8899a6ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shop']/parent::*</value>
      <webElementGuid>15980eb5-2c93-4cb5-9e26-de35467c4854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/shop')]</value>
      <webElementGuid>48a8fb97-2667-4be1-9fbd-9361fd410c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>b3fc4523-9af2-46b9-8c61-30691dbe2644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shop' and (text() = ' Shop' or . = ' Shop')]</value>
      <webElementGuid>5d4a49fa-9a03-47b3-8f04-ebe26b70052e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
