<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category_h-4 w-4 rounded border-gray-_cd3b7e</name>
   <tag></tag>
   <elementGuidId>5c154066-13b5-4b9b-8b28-673957c2794c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.h-4.w-4.rounded.border-gray-300.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff3be1d1-4f26-4106-848f-b10cfb7bc4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>961d0f13-1b56-4a5e-887a-a4599ce3bc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-4 w-4 rounded border-gray-300 text-primary</value>
      <webElementGuid>7e67c212-4818-4dbf-a0da-cb8dbfd76f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>7400de5b-9c7f-4f15-9047-483fd6e53f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex flex-1 pt-16&quot;]/main[@class=&quot;h-full w-full flex-1&quot;]/div[@class=&quot;pt-2&quot;]/div[@class=&quot;relative mx-auto max-w-7xl&quot;]/div[@class=&quot;m-6 flex flex-col gap-6 sm:flex-row&quot;]/div[@class=&quot;h-min overflow-hidden rounded-lg border border-gray-200 bg-white sm:w-1/4&quot;]/div[@class=&quot;border-b p-4&quot;]/ul[@class=&quot;space-y-3&quot;]/li[1]/label[@class=&quot;inline-flex items-center&quot;]/input[@class=&quot;h-4 w-4 rounded border-gray-300 text-primary&quot;]</value>
      <webElementGuid>2ab6d66d-6852-4fcd-932d-19dc06f71086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='17']</value>
      <webElementGuid>5cc4b084-dd4b-4d43-99e1-ec4aefd3ffd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div[2]/ul/li/label/input</value>
      <webElementGuid>9ef63fe5-7831-47d3-bbe9-a0a27ddb0c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6e770b26-1187-4596-b592-9efd55ad0299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>a7e459b8-8842-45d3-94a2-f1bec1c62125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
