<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1-1010-5050-100100-500500-10001000</name>
   <tag></tag>
   <elementGuidId>433951eb-66f5-4b76-b9e7-891e2c2ec18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='num_employee']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#num_employee</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e36be015-afc1-4ac5-b2de-d06bba93d8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>num_employee</value>
      <webElementGuid>348a7f34-cc6c-43e3-bc7b-717d0fc78eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>num_employee</value>
      <webElementGuid>fea77741-e165-413d-927f-6d94e2c46e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>17c45bd5-303d-49e8-aed2-032d2d6e32ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select number of employee</value>
      <webElementGuid>86876d78-2eb3-489d-951f-2e94bb188d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 px-3 py-2 text-neutral/on-surface ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>dafde0b1-5bf9-4226-b3c6-0d7dfb51fc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1-1010-5050-100100-500500-10001000+</value>
      <webElementGuid>cbe6742b-41ee-468b-bf44-4f2594d17426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;num_employee&quot;)</value>
      <webElementGuid>8d214172-934d-4e24-ae82-53f87463ad66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='num_employee']</value>
      <webElementGuid>667bda9b-3734-4e65-8531-cd2d40a0963d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[2]/div/div/form/div/div[8]/div[2]/div[2]/select</value>
      <webElementGuid>654e355d-f768-4ee5-a33f-621f2d9fc676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimate Number of employees'])[1]/following::select[1]</value>
      <webElementGuid>c5687423-f933-4a2c-a69c-a53ac09583fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code'])[1]/following::select[1]</value>
      <webElementGuid>9be1be57-14fd-4ff7-8716-bdc9162aca9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to the'])[1]/preceding::select[1]</value>
      <webElementGuid>bcdf16dd-7afa-4649-aee5-4635dd782b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::select[1]</value>
      <webElementGuid>70728704-42bb-4b11-ad5b-1bfae482b6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div[2]/select</value>
      <webElementGuid>86ca8d2a-f535-45df-a505-4b481974bf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'num_employee' and @name = 'num_employee' and @placeholder = 'Select number of employee' and (text() = '1-1010-5050-100100-500500-10001000+' or . = '1-1010-5050-100100-500500-10001000+')]</value>
      <webElementGuid>51377ce5-da4e-47bc-99bb-122b0c1941d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
