<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite Guest Mode Overview</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a8f4d144-4306-46ae-9bce-8bf7973eeeaf</testSuiteGuid>
   <testCaseLink>
      <guid>6990f1e4-8de4-4270-b69a-9c50f054103f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/TCUI_GMOverview_0001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a615f0c-8f68-420f-a139-162ecd7ecdec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68f9c1df-774c-4df0-bf63-f29cff05ba39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/TCUI_GMOverviewAC_0002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44c17c82-43d5-4479-9cd2-6f97e333cce7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ec77994-dd22-4a05-91e8-e520525fdabc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/TCUI_GMOverviewA_0003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df4fe998-7581-4a73-9e42-29813cd1972d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e197676-61a1-43b8-acf8-98b6cd09d7fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/TCUI_GMOverviewPE_0005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73b30b0d-9d29-435d-8aa2-54ac61f81496</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e83cbb26-807f-450d-a1e9-35b5ebe33afc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/TCUI_GMOverviewROI_0004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90483ae7-4da0-411c-a174-f0c3fd25439b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a919042e-d27c-4d47-b836-a9c0609866af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/TCUI_GMOverview_0001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a615f0c-8f68-420f-a139-162ecd7ecdec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5205c833-2ec0-4932-b9cf-d71772fffa72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/Variable_GMOverviewAC_0002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30dfc920-3ad4-4795-8919-d9ffc559b89a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2de9ada2-90d1-4f76-b6be-7c0467e03139</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/Variable_GMOverviewA_0003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02d89dc0-bc88-4c0e-b5ee-e7c206d312b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b5b35a8-90ba-43b7-b3ac-6feb53ff2d26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/Variable_GMOverviewPE_0005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d4a7fcc-f1ed-45d8-ae42-fe3ca10d6017</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e74ca5f7-952b-428c-9721-0572913871b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/Variable_GMOverviewROI_0004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72bf0aac-c0b7-43c4-9cec-a78ebc606d0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da4d8037-dfe6-401e-b740-32c365894222</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Guest Mode Overview/Variable_GMOverview_0001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d53b057f-249d-4fea-96e0-ee27acde1061</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
