<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Support</name>
   <tag></tag>
   <elementGuidId>77339256-0af3-4ece-8222-7ad222931d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-v-0-10 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='headlessui-menu-item-v-0-10']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3cdc1a75-5dd4-46a3-9a1d-3378bcb5497e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Support</value>
      <webElementGuid>3b8fae80-f079-4c62-9d1f-d55ed416478c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-v-0-10&quot;)/span[1]</value>
      <webElementGuid>251445f2-2a63-48fd-a6d8-d60aca4a5f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='headlessui-menu-item-v-0-10']/span</value>
      <webElementGuid>b1730126-3991-4a45-907f-25706e6b91ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>ea70f073-7e16-402a-8407-292589c3755a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Support' or . = 'Support')]</value>
      <webElementGuid>5ea11714-a647-4a01-aefa-cf0410e741c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
