<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ArjawinangunAstanajapuraBandungBanja_42c8d7</name>
   <tag></tag>
   <elementGuidId>4f10d1a2-c065-4c58-8fa3-06d66d202c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>405ac44a-6eec-4ff7-9335-ee2bb167adfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>cc8c55b9-c765-40fc-8607-4421999bb1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>d3b1864c-259d-4156-8bfc-c627c4f34172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 px-3 py-2 text-neutral/on-surface ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>90b45d13-9e73-4321-9d90-1240c47f3ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ArjawinangunAstanajapuraBandungBanjarBanjaranBekasiBogorCaringinCiamisCiampeaCibinongCicurugCikampekCikarangCikupaCileungsirCileunyiCimahiCiputatCiranjang-hilirCirebonCiteureupDepokIndramayuJatibarangJatiwangiKabupaten BandungKabupaten Bandung BaratKabupaten BekasiKabupaten BogorKabupaten CiamisKabupaten CianjurKabupaten CirebonKabupaten GarutKabupaten IndramayuKabupaten KarawangKabupaten KuninganKabupaten MajalengkaKabupaten PangandaranKabupaten PurwakartaKabupaten SubangKabupaten SukabumiKabupaten SumedangKabupaten TasikmalayaKarangampelKarangsembungKawaluKlangenanKota BandungKota BanjarKota BekasiKota BogorKota CimahiKota CirebonKota DepokKota SukabumiKota TasikmalayaKresekKuninganLembangMajalengkaMargahayukencanaNgawiPadalarangPalimananPamanukanPameungpeukPamulangParungPasarkemisPasehPelabuhanratuPlumbonPurwakartaRajapolahRengasdengklokSawanganSepatanSerpongSingaparnaSoreangSukabumiSumberSumedangSumedang UtaraTasikmalayaTeluknagaWanarajaWeru</value>
      <webElementGuid>52a5a043-0b5b-4a60-8f85-981cb873c5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>f5c02f6b-9d23-42c6-9bc4-21049b5cf888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>6f530faf-f0b3-4a1a-87b5-770f1aa81a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[2]/div/div/form/div/div[4]/div/div[2]/select</value>
      <webElementGuid>e31cb4e7-e093-4c98-a89b-4ec630387f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>398c9d9b-0dcc-4dea-bca0-80935cc15291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[2]</value>
      <webElementGuid>6bac4a6f-9d75-4608-99e5-6ad0579871b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code'])[1]/preceding::select[1]</value>
      <webElementGuid>7259c352-9518-4bf7-98a7-f8fa6e85bea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::select[1]</value>
      <webElementGuid>cbbdf616-0ab3-4906-852b-626ea951830c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/select</value>
      <webElementGuid>8eee97a4-e496-4616-ae34-19fa93df74cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and @name = 'city' and (text() = 'ArjawinangunAstanajapuraBandungBanjarBanjaranBekasiBogorCaringinCiamisCiampeaCibinongCicurugCikampekCikarangCikupaCileungsirCileunyiCimahiCiputatCiranjang-hilirCirebonCiteureupDepokIndramayuJatibarangJatiwangiKabupaten BandungKabupaten Bandung BaratKabupaten BekasiKabupaten BogorKabupaten CiamisKabupaten CianjurKabupaten CirebonKabupaten GarutKabupaten IndramayuKabupaten KarawangKabupaten KuninganKabupaten MajalengkaKabupaten PangandaranKabupaten PurwakartaKabupaten SubangKabupaten SukabumiKabupaten SumedangKabupaten TasikmalayaKarangampelKarangsembungKawaluKlangenanKota BandungKota BanjarKota BekasiKota BogorKota CimahiKota CirebonKota DepokKota SukabumiKota TasikmalayaKresekKuninganLembangMajalengkaMargahayukencanaNgawiPadalarangPalimananPamanukanPameungpeukPamulangParungPasarkemisPasehPelabuhanratuPlumbonPurwakartaRajapolahRengasdengklokSawanganSepatanSerpongSingaparnaSoreangSukabumiSumberSumedangSumedang UtaraTasikmalayaTeluknagaWanarajaWeru' or . = 'ArjawinangunAstanajapuraBandungBanjarBanjaranBekasiBogorCaringinCiamisCiampeaCibinongCicurugCikampekCikarangCikupaCileungsirCileunyiCimahiCiputatCiranjang-hilirCirebonCiteureupDepokIndramayuJatibarangJatiwangiKabupaten BandungKabupaten Bandung BaratKabupaten BekasiKabupaten BogorKabupaten CiamisKabupaten CianjurKabupaten CirebonKabupaten GarutKabupaten IndramayuKabupaten KarawangKabupaten KuninganKabupaten MajalengkaKabupaten PangandaranKabupaten PurwakartaKabupaten SubangKabupaten SukabumiKabupaten SumedangKabupaten TasikmalayaKarangampelKarangsembungKawaluKlangenanKota BandungKota BanjarKota BekasiKota BogorKota CimahiKota CirebonKota DepokKota SukabumiKota TasikmalayaKresekKuninganLembangMajalengkaMargahayukencanaNgawiPadalarangPalimananPamanukanPameungpeukPamulangParungPasarkemisPasehPelabuhanratuPlumbonPurwakartaRajapolahRengasdengklokSawanganSepatanSerpongSingaparnaSoreangSukabumiSumberSumedangSumedang UtaraTasikmalayaTeluknagaWanarajaWeru')]</value>
      <webElementGuid>3f84ad33-a1e7-469f-9d92-d4f0770463cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
