<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign In Now_mr- flex h-5 w-5 items-cent_b36b6e</name>
   <tag></tag>
   <elementGuidId>41cd805d-1e85-4904-ad59-afdedc16fc8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/div/div[2]/div/div/div[2]/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mr-.flex.h-5.w-5.items-center.justify-center.rounded-full.border-2.border-gray-300.bg-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>997d7dd5-d657-4383-b7c8-6c3bb3d25acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr- flex h-5 w-5 items-center justify-center rounded-full border-2 border-gray-300 bg-white</value>
      <webElementGuid>eba3af40-3a07-4c0a-95bb-c95aac11be99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[1]/div[1]/div[@class=&quot;flex h-full w-full flex-col bg-white lg:flex-row&quot;]/div[@class=&quot;flex-2 w-full p-8 lg:p-28&quot;]/div[@class=&quot;flex flex-col items-stretch justify-start gap-12&quot;]/div[@class=&quot;flex w-full gap-4&quot;]/label[@class=&quot;flex flex-1 cursor-pointer items-center rounded-lg border border-gray-300 px-4 py-3 text-base font-medium transition-all duration-300 border-neutral/outline bg-white text-neutral/on-surface&quot;]/div[@class=&quot;mr- flex h-5 w-5 items-center justify-center rounded-full border-2 border-gray-300 bg-white&quot;]</value>
      <webElementGuid>949e22c9-ba91-4821-9883-8e584c5da61e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[2]/div/div/div[2]/label/div</value>
      <webElementGuid>86b5c583-67e6-48a9-bf50-22097451b41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In Now'])[1]/following::div[2]</value>
      <webElementGuid>5e998df5-9fcd-4afc-976b-e834dcde337d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already have an account?'])[1]/following::div[2]</value>
      <webElementGuid>b59e9a49-44dc-44ca-8f38-0d90c808e6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual'])[1]/preceding::div[1]</value>
      <webElementGuid>c9a66c1a-d29b-40f7-880e-781d37ccbd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/preceding::div[3]</value>
      <webElementGuid>d21f9691-1571-47a1-8fae-e0db69aa12ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>c28dbf1b-b024-4f76-bf9e-13a44496a8e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
