<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ArjawinangunAstanajapuraBandungBanja_42c8d7</name>
   <tag></tag>
   <elementGuidId>b3c0da78-db7a-4812-9ff1-e9fc2905c420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a1aa4d3d-9604-4fb5-a4c6-1d41a675d07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>22c63bd3-af4c-4fc6-94d9-d63ef8ca946a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>27e2ed91-3b5b-455d-aeeb-20809d13da6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 px-3 py-2 text-neutral/on-surface ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>9fad587e-de4c-42ac-9f28-0abf23de583f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ArjawinangunAstanajapuraBandungBanjarBanjaranBekasiBogorCaringinCiamisCiampeaCibinongCicurugCikampekCikarangCikupaCileungsirCileunyiCimahiCiputatCiranjang-hilirCirebonCiteureupDepokIndramayuJatibarangJatiwangiKabupaten BandungKabupaten Bandung BaratKabupaten BekasiKabupaten BogorKabupaten CiamisKabupaten CianjurKabupaten CirebonKabupaten GarutKabupaten IndramayuKabupaten KarawangKabupaten KuninganKabupaten MajalengkaKabupaten PangandaranKabupaten PurwakartaKabupaten SubangKabupaten SukabumiKabupaten SumedangKabupaten TasikmalayaKarangampelKarangsembungKawaluKlangenanKota BandungKota BanjarKota BekasiKota BogorKota CimahiKota CirebonKota DepokKota SukabumiKota TasikmalayaKresekKuninganLembangMajalengkaMargahayukencanaNgawiPadalarangPalimananPamanukanPameungpeukPamulangParungPasarkemisPasehPelabuhanratuPlumbonPurwakartaRajapolahRengasdengklokSawanganSepatanSerpongSingaparnaSoreangSukabumiSumberSumedangSumedang UtaraTasikmalayaTeluknagaWanarajaWeru</value>
      <webElementGuid>4f991d91-ec3b-4369-8545-bc52ddea043e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>090870f8-a0fc-4124-98a2-370543a481d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>63b03aef-ce2b-4ce7-ae35-efe8edde6540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[2]/div/div/form/div/div[4]/div/div[2]/select</value>
      <webElementGuid>e0af8622-0464-402a-b9e4-183269ead53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>5f1e5f49-8422-4634-b8a0-31c87c3546bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[2]</value>
      <webElementGuid>20d7de3b-d81e-492c-bd03-7a991a3f3090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code'])[1]/preceding::select[1]</value>
      <webElementGuid>4950cfd7-12b6-4ae9-a0a3-5709275ae48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::select[1]</value>
      <webElementGuid>59bb8cc9-9920-464e-881a-1751b1e1856b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/select</value>
      <webElementGuid>2f15f992-c53b-44f5-8088-dbb18be827c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and @name = 'city' and (text() = 'ArjawinangunAstanajapuraBandungBanjarBanjaranBekasiBogorCaringinCiamisCiampeaCibinongCicurugCikampekCikarangCikupaCileungsirCileunyiCimahiCiputatCiranjang-hilirCirebonCiteureupDepokIndramayuJatibarangJatiwangiKabupaten BandungKabupaten Bandung BaratKabupaten BekasiKabupaten BogorKabupaten CiamisKabupaten CianjurKabupaten CirebonKabupaten GarutKabupaten IndramayuKabupaten KarawangKabupaten KuninganKabupaten MajalengkaKabupaten PangandaranKabupaten PurwakartaKabupaten SubangKabupaten SukabumiKabupaten SumedangKabupaten TasikmalayaKarangampelKarangsembungKawaluKlangenanKota BandungKota BanjarKota BekasiKota BogorKota CimahiKota CirebonKota DepokKota SukabumiKota TasikmalayaKresekKuninganLembangMajalengkaMargahayukencanaNgawiPadalarangPalimananPamanukanPameungpeukPamulangParungPasarkemisPasehPelabuhanratuPlumbonPurwakartaRajapolahRengasdengklokSawanganSepatanSerpongSingaparnaSoreangSukabumiSumberSumedangSumedang UtaraTasikmalayaTeluknagaWanarajaWeru' or . = 'ArjawinangunAstanajapuraBandungBanjarBanjaranBekasiBogorCaringinCiamisCiampeaCibinongCicurugCikampekCikarangCikupaCileungsirCileunyiCimahiCiputatCiranjang-hilirCirebonCiteureupDepokIndramayuJatibarangJatiwangiKabupaten BandungKabupaten Bandung BaratKabupaten BekasiKabupaten BogorKabupaten CiamisKabupaten CianjurKabupaten CirebonKabupaten GarutKabupaten IndramayuKabupaten KarawangKabupaten KuninganKabupaten MajalengkaKabupaten PangandaranKabupaten PurwakartaKabupaten SubangKabupaten SukabumiKabupaten SumedangKabupaten TasikmalayaKarangampelKarangsembungKawaluKlangenanKota BandungKota BanjarKota BekasiKota BogorKota CimahiKota CirebonKota DepokKota SukabumiKota TasikmalayaKresekKuninganLembangMajalengkaMargahayukencanaNgawiPadalarangPalimananPamanukanPameungpeukPamulangParungPasarkemisPasehPelabuhanratuPlumbonPurwakartaRajapolahRengasdengklokSawanganSepatanSerpongSingaparnaSoreangSukabumiSumberSumedangSumedang UtaraTasikmalayaTeluknagaWanarajaWeru')]</value>
      <webElementGuid>6acb8098-9ecf-450b-bd8e-950804987220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
