<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AdiwernaAmbarawaBaekrajanBakiBalapul_32e880</name>
   <tag></tag>
   <elementGuidId>33116694-aeee-4130-affa-08bc9a6baa84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f3b383dd-1f35-43aa-a8f7-5ab37987e586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>2db66713-f244-4ea7-b61c-66b725789307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>5e677617-6e23-4914-98a7-4f0947eaf670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-md border-0 px-3 py-2 text-neutral/on-surface ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-sky-600 sm:text-sm sm:leading-6</value>
      <webElementGuid>21cbcf6b-3442-4c08-8bd8-ed6e5fad33b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AdiwernaAmbarawaBaekrajanBakiBalapulangBanyumasBatangBaturadenBloraBoyolaliBuaranBulakambaCandi PrambananCeperCepuColomaduComalDelangguDemakDukuhturiGatakGebogGombongGrogolGunung KendilJatenJatirotoJekuloJogonalanJuwanaKabupaten BanjarnegaraKabupaten BanyumasKabupaten BatangKabupaten BloraKabupaten BoyolaliKabupaten BrebesKabupaten CilacapKabupaten DemakKabupaten GroboganKabupaten JeparaKabupaten KaranganyarKabupaten KebumenKabupaten KendalKabupaten KlatenKabupaten KudusKabupaten MagelangKabupaten PatiKabupaten PekalonganKabupaten PemalangKabupaten PurbalinggaKabupaten PurworejoKabupaten RembangKabupaten SemarangKabupaten SragenKabupaten SukoharjoKabupaten TegalKabupaten TemanggungKabupaten WonogiriKabupaten WonosoboKaranganomKartasuraKebonarunKedungwuniKetanggunganKlatenKota MagelangKota PekalonganKota SalatigaKota SemarangKota SurakartaKota TegalKroyaKudusKutoarjoLasemLebaksiuMagelangMajenangMargasariMertoyudanMlonggoMranggenMuntilanNgemplakPatiPecangaanPekalonganPemalangPurbalinggaPurwodadiPurwokertoRandudongkalRembanganSalatigaSelogiriSemarangSidarejaSlawiSokarajaSragenSurakartaTarubTayuTegalTrucukUngaranWangonWediWelahanWeleriWiradesaWonopringgoWonosobo</value>
      <webElementGuid>95a4980c-0775-4f2f-937c-dcb80370a826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>99ff7523-6546-4bdd-bd3f-32875f00727b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>a6e86599-41ba-407e-bf2e-023df784020e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[2]/div/div/form/div/div[6]/div[2]/div[2]/select</value>
      <webElementGuid>b7d14e69-bef2-4c61-885d-494683653155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>be2728dc-15e0-4f3b-8e21-adf1448759bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[2]</value>
      <webElementGuid>1ec7d1a1-8729-4de3-b66b-1baa95bc950e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::select[1]</value>
      <webElementGuid>ed348871-92aa-4c19-a090-e3ca0d13ec67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code'])[1]/preceding::select[1]</value>
      <webElementGuid>342d4248-3ab2-4529-bb68-bf2fc2b7b973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[2]/select</value>
      <webElementGuid>0dd30692-409a-48be-a436-2751251f7a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and @name = 'city' and (text() = 'AdiwernaAmbarawaBaekrajanBakiBalapulangBanyumasBatangBaturadenBloraBoyolaliBuaranBulakambaCandi PrambananCeperCepuColomaduComalDelangguDemakDukuhturiGatakGebogGombongGrogolGunung KendilJatenJatirotoJekuloJogonalanJuwanaKabupaten BanjarnegaraKabupaten BanyumasKabupaten BatangKabupaten BloraKabupaten BoyolaliKabupaten BrebesKabupaten CilacapKabupaten DemakKabupaten GroboganKabupaten JeparaKabupaten KaranganyarKabupaten KebumenKabupaten KendalKabupaten KlatenKabupaten KudusKabupaten MagelangKabupaten PatiKabupaten PekalonganKabupaten PemalangKabupaten PurbalinggaKabupaten PurworejoKabupaten RembangKabupaten SemarangKabupaten SragenKabupaten SukoharjoKabupaten TegalKabupaten TemanggungKabupaten WonogiriKabupaten WonosoboKaranganomKartasuraKebonarunKedungwuniKetanggunganKlatenKota MagelangKota PekalonganKota SalatigaKota SemarangKota SurakartaKota TegalKroyaKudusKutoarjoLasemLebaksiuMagelangMajenangMargasariMertoyudanMlonggoMranggenMuntilanNgemplakPatiPecangaanPekalonganPemalangPurbalinggaPurwodadiPurwokertoRandudongkalRembanganSalatigaSelogiriSemarangSidarejaSlawiSokarajaSragenSurakartaTarubTayuTegalTrucukUngaranWangonWediWelahanWeleriWiradesaWonopringgoWonosobo' or . = 'AdiwernaAmbarawaBaekrajanBakiBalapulangBanyumasBatangBaturadenBloraBoyolaliBuaranBulakambaCandi PrambananCeperCepuColomaduComalDelangguDemakDukuhturiGatakGebogGombongGrogolGunung KendilJatenJatirotoJekuloJogonalanJuwanaKabupaten BanjarnegaraKabupaten BanyumasKabupaten BatangKabupaten BloraKabupaten BoyolaliKabupaten BrebesKabupaten CilacapKabupaten DemakKabupaten GroboganKabupaten JeparaKabupaten KaranganyarKabupaten KebumenKabupaten KendalKabupaten KlatenKabupaten KudusKabupaten MagelangKabupaten PatiKabupaten PekalonganKabupaten PemalangKabupaten PurbalinggaKabupaten PurworejoKabupaten RembangKabupaten SemarangKabupaten SragenKabupaten SukoharjoKabupaten TegalKabupaten TemanggungKabupaten WonogiriKabupaten WonosoboKaranganomKartasuraKebonarunKedungwuniKetanggunganKlatenKota MagelangKota PekalonganKota SalatigaKota SemarangKota SurakartaKota TegalKroyaKudusKutoarjoLasemLebaksiuMagelangMajenangMargasariMertoyudanMlonggoMranggenMuntilanNgemplakPatiPecangaanPekalonganPemalangPurbalinggaPurwodadiPurwokertoRandudongkalRembanganSalatigaSelogiriSemarangSidarejaSlawiSokarajaSragenSurakartaTarubTayuTegalTrucukUngaranWangonWediWelahanWeleriWiradesaWonopringgoWonosobo')]</value>
      <webElementGuid>c718f21a-2e7c-4f51-9271-39b8305ff37a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
